### ISSUE TITLE
ERROR: Can't find config file: .jshintrc

### ISSUE THREAD

**Issue by packytagliaferro** [synapticism/wordpress-gulp-bower-sass#11]
I ran `gulp` after `npm install` and adding 2 new dependenceis I wanted (Bourbon and Neat). I got this error

`Packys-MacBook-Pro:themes PackyTagliaferro$ gulp
[11:05:28] Using gulpfile ~/Sites/SassGulpBowerWP.com/wp-content/themes/gulpfile.js
[11:05:28] Starting 'images'...
[11:05:28] Starting 'scripts-lint'...
ERROR: Can't find config file: .jshintrc`

Looks like the gulp-jshint is missing a config file when it got downloaded??

**Comment by Annalyn** [comment]
Hello packy, try to remove yung node modules folder and type npm install again. It solves the issue most of the times.

**Comment by packytagliaferro** [comment]
I tried removing it a few times with no luck. I got it running once, but not sure how. I just do the install as told and so far I am batting 1 for 20 on this

**Comment by Annalyn** [comment]
Hello packy, I tried to clone this on my computer.  Once cloned,  I added bourbon and neat on my bower.json and then typed "npm install" I don't see any error when it's done.  I suggest that you add bourbon and neat on your bower.json file before you do the npm install and it will work perfectly fine. Here is the tutorial link on how to add bourbon and neat to your bower dev dependencies: http://culttt.com/2013/12/09/adding-bourbon-and-bourbon-neat-with-bower/

Hope it helps.

**Comment by packytagliaferro** [comment]
The last 4 times I have not even added buorbon or neat. Just did a clean install.

**Comment by Annalyn** [comment]
Did you get the same error?

**Comment by packytagliaferro** [comment]
Same issue. The only way I got this thing to work is if I have it set like this:

`sitefolder/wp-content/themes/wordpress-gulp-bower-sass/package contents`

if I have it like this it doesnt work. I wonder if its looking for its old root folder name?

`sitefolder/wp-content/themes/package contents`

**Comment by Annalyn** [comment]
I don't do it that way.  I clone this repo on my desktop and then symlink the build folder on my wordpress/wp-content/themes and when I am ready to put the site live i run "gulp dist" and my new theme will be inside the dist folder.

At my work,  I created a theme folder for all our clients WordPress theme and then symlink the theme for appropriate site which is located on the htdocs folder (I use MAMP)

Try to execute the step by step instruction on the Readme.md and everything will work fine. Here is how to symlink your build folder to your wordpress theme folder: ln -s ~/dev/themes/my-theme/build ~/dev/localhost/wp/wp-content/themes/my-theme

The organization folder explains how src, build and dist folder works.

**Comment by packytagliaferro** [comment]
I figured it out. I was always copying and pasting the files to move them into the directory I wanted. The .jshintrc file is hidden so was never getting pulled from one folder to the next. Dumb mistake.

**Comment by Annalyn** [comment]
I'm glad you figured it out :) happy coding!

**Comment by synapticism** [comment]
Thanks for the help @Annalyn :)
