### ISSUE TITLE
Any interest in SVG sprites?

### ISSUE THREAD

**Issue by synapticism** [synapticism/wordpress-gulp-bower-sass#13]
I have developed a technique for using Bower and Gulp to generate SVG sprite sheets from arbitrary source material, outlined here: http://synapticism.com/dev/roll-your-own-svg-sprite-sheets-with-bower-and-gulp/

Any thoughts about integrating this here? Would people find this useful?

**Comment by dbox** [comment]
Looks super interesting

**Comment by synapticism** [comment]
I thought it over and I'm going to leave it out of this project. It adds a lot of complexity for a feature not so many people will use.
