### ISSUE TITLE
img folder not transfering

### ISSUE THREAD

**Issue by packytagliaferro** [synapticism/wordpress-gulp-bower-sass#14]
I added an img folder in the src folder to hold images. When I ran "gulp" it did not transfer the folder to the build destination. I also tried "gulp dist" and that did not work either. I tried fixing it by changing the gulpconfig file like so:

```
images: {
    build: { // Copies images from `src` to `build`; does not optimize
      src: src+'img/**/*(*.png|*.jpg|*.jpeg|*.gif)'
    , dest: build
    }
  , dist: {
      src: [dist+'img/**/*(*.png|*.jpg|*.jpeg|*.gif)', '!'+dist+'screenshot.png']
    , imagemin: {
        optimizationLevel: 7
      , progressive: true
      , interlaced: true
      }
    , dest: dist
    }
  },
```

Hard coding in the img directory still did not bring it over. Am I missing something? Thanks.

**Comment by synapticism** [comment]
Are there any images in the `img` folder? I don't think it will copy empty directories.
