### ISSUE TITLE
[ENHANCEMENT] Automatic asset injection into header.php

### ISSUE THREAD

**Issue by vlkz** [synapticism/wordpress-gulp-bower-sass#2]
See: https://github.com/klei/gulp-inject

And/Or: https://github.com/jonkemp/gulp-useref

**Comment by synapticism** [comment]
@vlkz: Could you elaborate with a use case? I haven't played with these plugins but from looking at the docs it seems like a less optimal solution than using the WP internal `wp_enqueue_scripts` action method (which allows you to use `wp_localize_script` to pass script variables to the front-end and such).

**Comment by vlkz** [comment]
@synapticism I guess those do the same thing. I don't have a whole lot of experience with wordpress theme development :)

**Comment by synapticism** [comment]
Ah, okay. I'm going to close this one then. I don't always agree with the WordPress way but in this case the advantages of loading scripts and stylesheets from within WP are too numerous to list here ;)

For reference:
http://codex.wordpress.org/Function_Reference/wp_enqueue_script
http://codex.wordpress.org/Function_Reference/wp_enqueue_style
