### ISSUE TITLE
[Enhancement] Gulp Include

### ISSUE THREAD

**Issue by lukasbesch** [synapticism/wordpress-gulp-bower-sass#3]
Using [gulp-include](https://www.npmjs.com/package/gulp-include) would be a great feature by default so scripts can be bundled more easily without touching the gulpconfig.js but using snockets/sprockets

**Comment by synapticism** [comment]
@lukasbesch Similar to my comment in issue #2, is there a good argument for bypassing `wp_enqueue_scripts`?

**Comment by lukasbesch** [comment]
I don't want to bypass `wp_enqueue_scripts`, I want to keep my JS modular in multiple partials like my SCSS. Of course in the end, the main scripts would be enqueued to WordPress.
I know that this is possible by defining bundles and chunks in the gulpconfig.js but having a SASS-like `@import` functionality would make things easier.

**Comment by synapticism** [comment]
@lukasbesch I think I understand where you're coming from now. I don't see how `gulp-include` could be used to efficiently prepare multiple bundles for conditional loading in WP... but if you're not interested in that sort of functionality I see that there's nowhere to hook into and add such a thing. I'll ponder this one for a future update.

**Comment by synapticism** [comment]
I've thought it over and this is definitely in "nice to have" territory... but I'll leave the current script bundling method in place as it allows for more granular control to create more highly optimized WP themes. This should be easy enough to add to the workflow for anyone familiar with Gulp.
