### ISSUE TITLE
Docs to cover set up integration with Apache/NGNIX

### ISSUE THREAD

**Issue by gad2103** [synapticism/wordpress-gulp-bower-sass#4]
it would be nice to have some info on how to use this with apache and ngnix.

**Comment by synapticism** [comment]
@gad2103 The end product is just a theme; server configuration would seem to be out of scope for this project (unless I'm missing something here).

**Comment by gad2103** [comment]
It would just be helpful in the docs but technically you're right. I can
send a pr with my ideas
