### ISSUE TITLE
using node-sass (libsass) -- modifications to repo

### ISSUE THREAD

**Issue by dkebler** [synapticism/wordpress-gulp-bower-sass#7]
Trying to do a nodejs only setup.  Ok with and already using node-sass/libsass in other projects.    Seems your code is set up for this.  Can you explain the steps to drop ruby sass and use node-sass.  Maybe just put this in the readme or better yet have alternate repo and let users choose.  Thx

**Comment by synapticism** [comment]
Last time I checked libsass wasn't very mature but I added a task file to the "inactive tasks" folder that might act as something that could be swapped in. I'll take a closer look at things soon.

**Comment by dkebler** [comment]
Yes I saw the inactive tasks.  That is why I asked.

libsass works fine for me in my applications (sass libs) and I am trying
not to put ruby in my workflow just for sass.  Dumped compass as well.
http://sass-compatibility.github.io/
They are near daily active on their github repo and should be there soon
anyway.
https://github.com/sass/libsass/wiki/The-LibSass-Compatibility-Plan

So that's I why I suggested you make the option you have available now or
at least explain how to implement it.

Thx


On Fri, May 1, 2015 at 6:15 AM, Alexander Synaptic <notifications@github.com
> wrote:

> Last time I checked libsass wasn't very mature but I added a task file to
> the "inactive tasks" folder that might act as something that could be
> swapped in. I'll take a closer look at things soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synapticism/wordpress-gulp-bower-sass/issues/7#issuecomment-98130589>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by synapticism** [comment]
Ah, looks like things are much more mature than the last time I checked. I've got a working implementation on my HD, will test it a bit and then give this project a bump when it's ready for a closer look.

**Comment by synapticism** [comment]
I'm hitting a bit of a wall in testing gulp-sass and imports as outlined [here](https://github.com/dlmanning/gulp-sass/issues/235). What I think I'm going to do is make compiler a user-specified options and leave the more stable, working Ruby Sass compiler as the default.

**Comment by dkebler** [comment]
Agree, having a user option is clearly the best route.  Problems with
gulp-sass/node-sass not yours.  Appreciate you going forward with this.

On Sat, May 2, 2015 at 9:08 AM, Alexander Synaptic <notifications@github.com
> wrote:

> I'm hitting a bit of a wall in testing gulp-sass and imports as outlined
> here <https://github.com/dlmanning/gulp-sass/issues/235>. What I think
> I'm going to do is make compiler a user-specified options and leave the
> more stable, working Ruby Sass compiler as the default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synapticism/wordpress-gulp-bower-sass/issues/7#issuecomment-98374068>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by synapticism** [comment]
I just committed some changes but haven't formally bumped the version. If you'd like to check out libsass support, please do. Sourcemaps and everything seem to be working but I haven't been using this stuff in my regular work as of yet.

**Comment by synapticism** [comment]
I'm going to close this as libsass seems to be working well enough. Feel free to comment again if you experience and problems (or open a new issue if it's more specific).
