### ISSUE TITLE
sream error file to import not found scut/dist/scut

### ISSUE THREAD

**Issue by adamawesomeface** [synapticism/wordpress-gulp-bower-sass#8]
I just cloned the latest and installed everything from npm/bower.

Once I ran gulp i get the following:
```ruby
16:21:56] Using gulpfile ~/Copy/_baseLayouts/wp-gulp-sass-bower/gulpfile.js
[16:21:56] Starting 'images'...
[16:21:56] Starting 'scripts-lint'...
[16:21:57] Starting 'styles-libsass'...
[16:21:57] Starting 'theme-lang'...
[16:21:57] Starting 'theme-php'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: file to import not found or unreadable: scut/dist/scut
```

Let me know if more information can be provided.

**Comment by Annalyn** [comment]
Unfortunately, I got the same error today.

**Comment by synapticism** [comment]
I am not able to replicate but I bumped the version of Scut included in the project. Can you let me know if there is indeed a `scut/dist/_scut.scss` under `bower_components` after you've installed everything? And are you using the default libsass compiler or Ruby Sass?

**Comment by adamawesomeface** [comment]
Removed the project, did a new git clone.  Edited the gulpconfig.js to change project name and ran npm install.   Once I ran gulp.  Everything seemed to work just fine.   Thanks for the fix. it seems to have corrected the issue.   I am using the default libsass.

**Comment by synapticism** [comment]
That sounds like confirmation enough :) @Annalyn, let me know if you still have a problem and I'll re-open.

**Comment by Annalyn** [comment]
Not anymore.. you did an excellent job! What happened was it didn't generate a bower folder.  It works great now.

One small thing happened was I got a v8flags node error in gulp@3.8.8, but I fixed it by uninstalling gulp and re-installed it.  

Thank you for this great work @synapticism.  I like what you put together.

**Comment by synapticism** [comment]
:+1:
