### ISSUE TITLE
File not found "normalize"

### ISSUE THREAD

**Issue by MrViSiOn** [synapticism/wordpress-gulp-bower-sass#9]
Hi:

  I'm trying this proyect out and running "gulp dist" after npm install command, It throws me 

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: file to import not found or unreadable: normalize
Current dir: G:/Dropbox/htdocs/BancoDelTiempo/wp-content/themes/BdT/src/src/scss/

What I'm doing wrong?

**Comment by MrViSiOn** [comment]
I just install this normalize css http://necolas.github.io/normalize.css/ in scss directory and It works

I think you miss this up.

**Comment by synapticism** [comment]
Do you also have Bower installed? Did it retrieve all packages correctly?

**Comment by Annalyn** [comment]
There must be one character added or removed on your code, that always happen to me.
